// Auto-generated by scripts/copy-qe-version.mjs from quantecon/VERSION.yml.
// Source of truth is quantecon/VERSION.yml; do not hand-edit.
const qeVersion: string | null = "qe-v6";
export default qeVersion;
